import mutations from "./mutations.js";
import actions from "./actions.js";
import getters from "./getters.js";

export default {
  state() {
    return {
      preference: {
        updateApiStatus: false,
        pre_partner_age_min: "",
        pre_partner_age_max: "",
        pre_height_min: "",
        pre_height_max: "",
        pre_has_country_allow_prefference: "",
        pre_countries: [],
        pre_cities: [],
        preferred_countries: [],
        preferred_cities: [],
        pre_strength_of_character_rate: "",
        pre_look_and_appearance_rate: "",
        pre_religiosity_or_faith_rate: "",
        pre_manners_socialskill_ethics_rate: "",
        pre_emotional_maturity_rate: "",
        pre_good_listener_rate: "",
        pre_good_talker_rate: "",
        pre_wiling_to_learn_rate: "",
        pre_family_social_status_rate: "",
        pre_employment_wealth_rate: "",
        pre_education_rate: "",
        pre_religions: "1, 2, 3",
      },
      personalinformation: {
        updateApiStatus: false,
        // first_name: "",
        // last_name: "",
        // screen_name: "",
        // dob: null,
        // mobile_number: "",
        // mobile_country_code: "",
        // telephone_no: "",
        // gender: "",
        // height: "",
        // employment_status: "",
        // education_level_id: "",
        // religion_id: "",
        // ethnicity: "",
        // mother_tongue: "",
        // nationality: "",
        // country_of_birth: "",
        // current_residence: "",
        // address: "",
        // marital_status: "",
        // have_children: "false",
        // currently_living_with: "",
        // willing_to_relocate: "",
        // smoker: "",
        // language_speak: "",
        // hobbies_interests: "",
        // food_cuisine_like: "",
        // things_enjoy: "",
        // thankfull_for: "",
        // about: "",
      },
      familyinformation: {
        fathersName: "",
        mothersName: "",
        fathersProfession: "",
        mothersProfession: "",
        siblings: "",
        otherFamilyInfo: "",
        countryOfOrigin: "",
        updateApiStatus: false,
      },
      imageupload: {},
      countries: [],
      study_level_options: [],
      religion_options: [],
      occupations: {},
      review: {},
      successMessageTitle: "Success!",
      successMessage: "Data saved successfully, proceed to next step!",
      activePanel: 1,
    };
  },
  mutations,
  actions,
  getters,
};
