const ethnicities = [
  "Other",
  "Aboriginal",
  "Acehnese",
  "Acholi",
  "Adja",
  "Adja-Ewe",
  "Adja-Mina",
  "Afar",
  "Affar",
  "African",
  "African American",
  "African British",
  "African Descent",
  "Aimaq",
  "Akan",
  "Akebu",
  "Akha",
  "Akkposso",
  "Alaska Native",
  "Alawite",
  "Albanian",
  "Amak Negeri",
  "Amara",
  "American",
  "American Bangladeshi",
  "American Indian",
  "American Pakistani",
  "American Syrian",
  "Amerindian",
  "Amerindian Ancestory",
  "Amerinindian",
  "Amhara",
  "Amis",
  "Andorran",
  "An-lfe",
  "Anuak",
  "Any other Asian background",
  "Any other Black",
  "Any other Mixed",
  "Any other White background",
  "Arab",
  "Arab-Berber",
  "Argentinian",
  "Armenian",
  "Aruban",
  "Asian",
  "Asian American",
  "Asian British",
  "Assamese",
  "Assyrian",
  "Atayal",
  "Austonesian",
  "Australian",
  "Australian Aboriginal",
  "Australian African",
  "Australian Asian",
  "Australian Bangladeshi",
  "Australian Black",
  "Australian Caribbean",
  "Australian Indian",
  "Australian Pakistani",
  "Australian Tamil",
  "Australian White",
  "Austrian",
  "Azande",
  "Azerbajani",
  "Azeri",
  "Bada",
  "Baganda",
  "Bagisu",
  "Bai",
  "Baikeno",
  "Baka",
  "Bakasi",
  "Bakiga",
  "Bakongo",
  "Balck African",
  "Balinese",
  "Baloch",
  "Balochi",
  "Bambara",
  "Bangladeshi",
  "Banjarese",
  "Bantanese",
  "Bantu",
  "Banyankoie",
  "Bari",
  "Bariba",
  "Basarwa",
  "Bashkir",
  "Basoga",
  "Basque Minorities",
  "Basques",
  "Batak",
  "Baya",
  "Bedouin",
  "Beja",
  "Belarusian",
  "Belgian",
  "Bemba",
  "Bengali",
  "Bengali-Indian",
  "Berber",
  "Beriberi",
  "Betawi",
  "Bicol",
  "Bikol",
  "Binisaya",
  "Bisa",
  "Bisaya",
  "Bissa",
  "Black",
  "Black African",
  "Black American",
  "Black British",
  "Bobo",
  "Bongo",
  "Bosnia and Herzegovinian",
  "Bosniak",
  "Bosniak Muslim",
  "Bosniak other",
  "Brahman-Hill",
  "Brahui",
  "Bretons",
  "British",
  "British Arab",
  "British Arican-Caribbean",
  "British Asian",
  "British Bangladeshi",
  "British Chinese",
  "British Indian",
  "British Pakistani",
  "British Punjabi",
  "British Syrian",
  "Buginese",
  "Bulgarian",
  "Bumiputera",
  "Bunak",
  "Bunun",
  "Burman",
  "Burmese",
  "Buyei",
  "Bviri",
  "Cameroon Highlanders",
  "Canadian African",
  "Canadian Arab",
  "Canadian Asian",
  "Canadian Bangladeshi",
  "Canadian Bengali",
  "Canadian Black",
  "Canadian British",
  "Canadian Carribean",
  "Canadian English",
  "Canadian French",
  "Canadian Indian",
  "Canadian Irish",
  "Canadian Pakistani",
  "Canadian Syrian",
  "Canadian Tamil",
  "Caribbean",
  "Caribbean Background",
  "Caribbean British",
  "Cebuano",
  "Celtic",
  "Central American",
  "Cham",
  "Chamar",
  "Chamorro",
  "Chechen",
  "Chhettri",
  "Chilean",
  "Chinese",
  "Chola",
  "Chola Chola",
  "Chuvash",
  "Circassian",
  "Colombina",
  "Cook Island Maori",
  "Creole",
  "Crimean Tatar",
  "Croat",
  "Cuban",
  "Curacacaon",
  "Czech",
  "Dagara",
  "Dai",
  "Damai",
  "Dangme",
  "Danish",
  "Dayak",
  "Dendi",
  "Dholii",
  "Didinga",
  "Dinak (jieng)",
  "Dioula",
  "Domincan Republic",
  "Dominican",
  "Dominican Republican",
  "Dong",
  "Druze",
  "Dungotona",
  "Dutch",
  "Dutch African",
  "Dutch Arab",
  "Dutch Asian",
  "Dutch Bangladeshi",
  "Dutch Bengali",
  "Dutch Black",
  "Dutch Carribean",
  "Dutch Indian",
  "Dutch Pakistani",
  "Dutch Syrian",
  "Dutch Tamil",
  "East Indian",
  "East Indians",
  "Eastern Nigritic",
  "Egyptian",
  "Emirati",
  "English",
  "Equatorial Bantu",
  "European",
  "European African",
  "European Ancestry",
  "European Asian",
  "European Bangladeshi",
  "European Bengali",
  "European Black",
  "European Caribbean",
  "European Indian",
  "European Pakistani",
  "European Syrian",
  "European Tamil",
  "Ewe",
  "Fallata",
  "Fataluku",
  "Fertit",
  "Filipino",
  "Finnish",
  "Fon",
  "French",
  "French African",
  "French Arab",
  "French Asian",
  "French Bangladeshi",
  "French Bengali",
  "French Black",
  "French Caribbean",
  "French Indian",
  "French Pakistani",
  "French Syrian",
  "French Tamil",
  "Fulani",
  "Fur",
  "Futunian",
  "Galoli",
  "Gamo",
  "Garifuuna",
  "Gedeo",
  "German",
  "German African",
  "German Arab",
  "German Asian",
  "German Bangladeshi",
  "German Bengali",
  "German Black",
  "German Carribean",
  "German Indian",
  "German Pakistani",
  "German Syrian",
  "German Tamil",
  "Gibraltarian",
  "Gorani",
  "Greek",
  "Greenlandic",
  "Grusi",
  "Guan",
  "Guernsey",
  "Gujar",
  "Gujrati",
  "Gujrati British",
  "Gurage",
  "Gurma",
  "Gurung",
  "Gurunsi",
  "Guyanian",
  "Gypsy or Irish Traveller",
  "Hadiya",
  "Haitian",
  "Hakka",
  "Han Chinese",
  "Hani",
  "Hausa",
  "Hazara",
  "Hiligaynon",
  "Hispanic",
  "Hispanic and Latino American",
  "Hla'alua",
  "Hmong",
  "Hoa",
  "Hokio",
  "Hui",
  "Hungarian",
  "Hutu",
  "Ibibio",
  "Ijaw",
  "Imami",
  "Indian",
  "Indian British",
  "Indian Tamil",
  "Indignious (original people of my land)",
  "Indo-Aryan",
  "Indochinese",
  "Indonesian",
  "Iraqi",
  "Irish",
  "Irish Syrian",
  "Irish Traveller",
  "Ismailii",
  "Italian",
  "Italian African",
  "Italian Arab",
  "Italian Asian",
  "Italian Bangladeshi",
  "Italian Bengali",
  "Italian Black",
  "Italian Caribbean",
  "Italian Indian",
  "Italian Pakistani",
  "Italian Syrian",
  "Italian Tamil",
  "Iteso",
  "Izon",
  "Jamaican",
  "Japanese",
  "Jewish",
  "Jordanian",
  "Kabye",
  "Kaka'i",
  "Kakwa",
  "Kalanga",
  "Kalenjin",
  "Kamba",
  "Kami",
  "Kanak",
  "Kanakaravu",
  "Kanuri",
  "Kaonde",
  "Karakalpak",
  "Karen",
  "Katong",
  "Kavalan",
  "Kazakh",
  "Kefficho",
  "Kemak",
  "Kgalagdi",
  "Khmer",
  "Khmou",
  "Kikuyu",
  "Kimbundu",
  "Kinh",
  "Kirdi",
  "Kisii",
  "Koiri",
  "Korean",
  "Kosovar",
  "Kuku",
  "Kurd",
  "Kurdish",
  "Kuwaiti",
  "Kyrghyz",
  "Kyrgyg",
  "Lala",
  "Lamba",
  "Langi",
  "Lango",
  "Lao",
  "Latino",
  "Latvian",
  "Lenje",
  "Levantine",
  "Lezghin",
  "Lhotshampas",
  "Li",
  "Liechtensteiner",
  "Limbu",
  "Lithuanian",
  "Llcano",
  "LLonggo",
  "Lndi",
  "Lobi",
  "Lomwe",
  "Lozi",
  "Lue",
  "Lugbara",
  "Luhya",
  "Lunda",
  "Luo",
  "Lur",
  "Luvale",
  "Luxembourger",
  "Maasaai",
  "Macedonian",
  "Madurese",
  "Magar",
  "Makong",
  "Malay",
  "Malayo-Indonesian",
  "Malayo-Polynesian",
  "Malayo-Polynesian#Tetun",
  "Malaysian",
  "Maldivian",
  "Malinke",
  "Maltese",
  "Mambwe",
  "Manchu",
  "Mandari",
  "Mande",
  "Mandija",
  "Maori",
  "Maroon",
  "Mauritinian",
  "Maya",
  "M'baka",
  "Mboum",
  "Mbunda",
  "Melanesian",
  "Melanesian-papuna",
  "Membai",
  "Meru",
  "Mestico",
  "Mestizo",
  "Mestizo (Mixed Amerindian and White)",
  "Mexian",
  "Mexican",
  "Mexican American",
  "Miao",
  "Micronesian",
  "Minangkabau",
  "Mixed African",
  "Mixed Arab",
  "Mixed ethnicity",
  "Mixed European and Nativ eafrican",
  "Mole-Dagbon",
  "Molodovan",
  "Mon",
  "Mong",
  "Mongol",
  "Mongolian",
  "Montenegrin",
  "Moravian",
  "Moroccan",
  "Mossi",
  "Mozambiquian",
  "Muhajirs",
  "Mujikenda",
  "Multiple ethnic background",
  "Multiracial",
  "Muong",
  "Murie",
  "Namwanga",
  "Native Hawaaiian",
  "Native Hawaiian",
  "Ndebele",
  "Ndogo",
  "Neapalian",
  "Nepali",
  "New Zealander",
  "Newar",
  "Ngalop",
  "Ngoni",
  "Ni-vanuatu",
  "non-Melanesian",
  "North African",
  "North American",
  "Northern Irish",
  "Northwestern Bantu",
  "Norwegian",
  "Nsenga",
  "Nuba",
  "Nuer (Naath)",
  "Nung",
  "Nuristani",
  "Nusairi",
  "Orang Asli",
  "Oromo",
  "Other British",
  "Ottamari",
  "Ovimbundu",
  "Pacific Islander",
  "Paiwan",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Pamiri",
  "Para-Gourma",
  "Pashai",
  "Pashtun",
  "Pathan",
  "Persian",
  "Peruvian",
  "Peuhi",
  "Phouthay",
  "Polish",
  "Polynesian",
  "Portuguese",
  "Puerto Rican",
  "Punjabi",
  "Puyuma",
  "Qizilbash",
  "Rai",
  "Rakhine",
  "Romani",
  "Romanian",
  "Rukai",
  "Russian",
  "Ruthenian",
  "Sabaean-Mandaean",
  "Saint Lucian",
  "Saint Maartenian",
  "Saisiyat",
  "Sakizaya",
  "Samoan",
  "Sara",
  "Saraiki",
  "Sarki",
  "Sasak",
  "Scottish",
  "Scottish Syrian",
  "Seediq",
  "Sena",
  "Senufo",
  "Serb",
  "Serbian",
  "Setswaan",
  "Shabak",
  "Shan",
  "Shilluk (Chollio)",
  "Shona",
  "Sidama",
  "Silte",
  "Sindhi",
  "Sinhalese",
  "Slavic",
  "Slovak",
  "Slovene",
  "Somali",
  "Somalie",
  "Songhi",
  "Sotho",
  "South American",
  "South Asian",
  "Spanish",
  "Spanish African",
  "Spanish Arab",
  "Spanish Asian",
  "Spanish Bangladeshi",
  "Spanish Bengali",
  "Spanish Black",
  "Spanish Caribbean",
  "Spanish Indian",
  "Spanish Pakistani",
  "Spanish Syrian",
  "Spanish Tamil",
  "Sri Lankan Moors",
  "Sri Lankan Tamil",
  "Sri Lankian",
  "St Helenian",
  "Sudanese Arab",
  "Sundanese",
  "Surinamese",
  "Susu",
  "Swedish",
  "Swedish African",
  "Swedish arab",
  "Swedish Asian",
  "Swedish Bangladeshi",
  "Swedish Black",
  "Swedish Carribean",
  "Swedish Indian",
  "Swedish Pakistani",
  "Swedish Syrian",
  "Swedish Tamil",
  "Swiss",
  "Tagalog",
  "Tahitian",
  "Tai",
  "Tajik",
  "Talysh",
  "Tamang",
  "Tamil",
  "Tatar",
  "Teli",
  "Tem",
  "Thai",
  "Thakuri",
  "Thao",
  "Tharu",
  "Tibetan",
  "Tigray",
  "Tigrinya",
  "Tivo",
  "Togolese",
  "Tokelauan",
  "Tokodede",
  "Tonga Chewa",
  "Tongan",
  "Truku",
  "Tsonga",
  "Tsou",
  "Tswaana",
  "Tswan",
  "Tuareg",
  "Tuareg Belia",
  "Tuba",
  "Tujia",
  "Tumbuku",
  "Turkana",
  "Turkemn",
  "Turkic",
  "Turkish",
  "Turkmen",
  "Turkmen and Turkic",
  "Turkoman",
  "Tusi",
  "Tuvalian l -Kiribati",
  "Tuvaluan",
  "Tuvaluan (other)",
  "Uighur",
  "Ukranian",
  "Uruguayan",
  "Ushi",
  "Uyghur",
  "Uzbek",
  "Venezuelan",
  "Vietnamese",
  "Vlach",
  "Wallisian",
  "Waray",
  "Welaita",
  "Welsh",
  "Welsh Syrian",
  "White",
  "White American",
  "White and Asian",
  "White and Black African",
  "White and Black Caribbean",
  "White British",
  "Yadav",
  "Yagnobi",
  "Yakoma",
  "Yami",
  "Yao",
  "Yezidi",
  "Yezidi (Kurd)",
  "Yi",
  "Yoa-Lokpa",
  "Yoruba",
  "Yoruba Igbo",
  "Zambian",
  "Zanzibar-Arab",
  "Zarma",
  "Zhuang",
];
  export default ethnicities;
