const foods = [
    "Other",
    "Albanian",
    "Alfredo sauce",
    "Andhra",
    "Anglo-Indian",
    "Apple pie",
    "Apple sauce",
    "Arab",
    "Argentine",
    "Armenian",
    "Assyrian",
    "Awadhi",
    "Azerbaijani",
    "Bagel",
    "Baguette",
    "Baked potato",
    "Baklava",
    "Balochi",
    "Banana",
    "Banana bread",
    "Bangladeshi",
    "Belarusian",
    "Bengali",
    "Berbecue",
    "Berber",
    "Bibimbap",
    "Biscuits and gravy",
    "Blueberries",
    "Borek",
    "Borscht",
    "Brazilian",
    "Bread",
    "Broccoli",
    "Brownies",
    "Buddhist",
    "Bulgarian",
    "Bulgogi",
    "Burger",

    "Burritos",
    "Cajun",
    "Calzone",
    "Cantaloupe",
    "Cantonese",
    "Caribbean",
    "Cellophane Noodles",
    "Chechen",
    "Cheese",
    "Cheese cake",
    "Cheetos",
    "Chicken and chips",
    "Chicken curry",
    "Chicken nuggets",
    "Chicken pot pie",
    "Chicken tenders",
    "Chimichanga",
    "Chinese Islamic",
    "Chinese cuisine",
    "Chips",
    "Chocolate cake",
    "Chocolate chip cookie",
    "Chocolate strawberried",
    "Churros",
    "Chutney",
    "Circassian",
    "Cookies",
    "Corn",
    "Cranberry",
    "Cremeeschnitte",
    "Crepes",
    "Crimean Tatar",
    "Croissant",
    "Cream brulee",
    "Cypriot",
    "Danish",
    "Donuts",
    "Doritos",
    "Eggs",
    "Enchilada",
    "Enchiladas",
    "English",
    "Estonian",
    "Fajitas",
    "Falafel",
    "Filipino",
    "Fish &chips",
    "French",
    "French fries",
    "French toast",
    "Fried chicken",
    "Fried rice",
    "Fried zucchini blossoms",
    "Fudge",
    "Gaufre",
    "Georgian",
    "German",
    "Ginger brea",
    "Goan",
    "Goan Catholic",
    "Greek",
    "Green beans",
    "Grilled chicken",
    "Guacamole",
    "Gujarati",
    "Gyoza",
    "Gyro sandwich",
    "Honeydew",
    "Hot dogs",
    "Hyderabad",
    "Ice cream",
    "Ice cream cake",
    "Indian Chinese",
    "Indian cuisine",
    "Indonesian",
    "Inuit",
    "Irish",
    "Italian cuisine",
    "Italian-American",
    "Jamaican",
    "Japanese",
    "Jewish",
    "Kare",
    "Karnataka",
    "Kazakh",
    "Keralite",
    "Kimchi",
    "King prawn",
    "Kiwi",
    "Korean",
    "Kurdish",
    "Laksa",
    "Lamb chops",
    "Laotian",
    "Lasagna",
    "Lasagne",
    "Latvian",
    "Lebanese",
    "Lithuanian",
    "Louisiana Creole",
    "Mac and cheese",
    "Maharashtrian",
    "Makizushi",
    "Malay",
    "Malaysian Chinese cuisine",
    "Malaysian Indian cuisine",
    "Mangalorean",
    "Mango",
    "Marinara sauce",
    "Mashed potato",
    "Meat curry, beef",
    "Meat curry, lamb",
    "Meatballs",
    "Mediterranean cuisine",
    "Mexican",
    "Miso soup",
    "Mordovian",
    "Moussaaka",
    "Muffins",
    "Mughal",
    "Naan",
   
    "Nachos",
    "Native American",
    "Nepalese",
    "New Mexican",
    "Odia",
    "Olivebreadsticks",
    "Onigiri",
    "Onion rings",
    "Orange",
    "Pakistani",
    "Pancakes",
    "Panna cotta",
    "Parmigiano Reggiano",
    "Parsi",
    "Pashtun",
    "Pasta",
    "Pavlova",
    "Peaches",
    "Peanuts",
    "Pennsylvania Dutch",
    "Peranakan",
    "Persian",
    "Peruvian",
    "Pizza",

    "Pizza Margherita",
    "Polish",
    "Pommes frites",
    "Popcorn",
    "Portuguese",
    "Potato",
    "Potato chips",
    "Prawn",
    "Pretzel",
    "Pudding",
    "Pumpkin pie",
    "Punjabi",
    "Quesadilla",
    "Quiche",
    "Rajasthani",
    "Raspberries",
    "Ravioli",
    "Ribs",
    "Roasted chicken",
    "Romanian",
    "Russian",
    "Salad",
    "Salsa",
    "Sami",
    "Sarma",
    "Satay",
    "Serbian",
    "Shabu-shabu",
    "Shrimp",
    "Sindhi",
    "Slovak",
    "Slovenian",
    "Somali",
    "Souffle",
    "Soup",
    "South Indian",
    "Soviet",
    "Spanish",
    "Spring rolls",
    "Sri Lankan",
    "Steak",
    "Strawberries",
    "Stuffing",
    "Submarine sandwich",
    "Sushi",
    "Sweet potatoes",
    "Tacos",
    "Taiwanese",
    "Tamal",
    "Tamale",
    "Tamil",
    "Tatar",
    "Tater tots",
    "Tempura",
    "Teriyaki",
    "Thai",
    "Thai curry",
    "Tofu",
    "Tomato",
    "Tonkatsu",
    "Tortas",
    "Turkey",
    "Turkish",
    "Udon",
    "Udupi",
    "Ukrainian",
    "Vietnamese",
    "Wings and chips",
    "Yamal",
    "Zambian",
    "Zanzibari",
];

export default foods;
