const languages = [
  "Other",
  "Afrikaans",
  "Akan",
  "Algerian Arabic",
  "Amharic",
  "Arabic",
  "Arabic -Classsic",
  "Arabic -Modern",
  "Arabic -Syrian",
  "Assamese",
  "Awadhi",
  "Balochi",
  "Bavarian",
  "Belarusian",
  "Bangla",
  "Bhojpuri",
  "Brazilain",
  "Burmese",
  "Cantonese",
  "Cebuano",
  "Chewa",
  "Chhattisgarhi",
  "Chinese",
  "Cypriot",
  "Cypriot Arabic",
  "Czech",
  "Deccan",
  "Dhundhari",
  "Dutch",
  "Eastern Min",
  "Eastern Punjabi",
  "Egyptian Arabic",
  "English",
  "French",
  "Fula",
  "Gaelic",
  "Gan",
  "Gan Chinese",
  "German",
  "Greek",
  "Gujrati",
  "Haitian Creole",
  "Hakka",
  "Hakka Chinese",
  "Haryanvi",
  "Hausa",
  "Hebrew",
  "Hejaz Arabic",
  "Hindi",
  "Hmong",
  "Hungarian",
  "Igbo",
  "Indonesian",
  "Indonesian Malay",
  "Iranian Persian",
  "Italian",
  "Japanese",
  "Jin Chinese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Kinyarwanda",
  "Kirundi",
  "Konkani",
  "Korean",
  "Kosovan",
  "Kurdish",
  "Landha",
  "Latin",
  "Llocano",
  "Madurse",
  "Magahai",
  "Maithili",
  "Malagasy",
  "Malay",
  "Malay Bahasa",
  "Malayalam",
  "Manadarin Chinese",
  "Marathi",
  "Marwari",
  "Mesopotamian Arabic",
  "Mexican",
  "Min Bei Chinese",
  "Min Dong Chinese",
  "Min nan Chinese",
  "Moroccan Arabic",
  "Mossssi",
  "Nepali",
  "Nigerian Fulfulde",
  "North Levatine Arabic",
  "Northern Uzbek",
  "Northerrn Kurdish",
  "Odia",
  "Ormomo",
  "Pashto-Northern",
  "Persian",
  "Peshto",
  "Peshto - Southern",
  "Polish",
  "Portugese",
  "Punjabi",
  "Quechua",
  "Romanian",
  "Rundi",
  "Russian",
  "Sa'aidi Arabic",
  "Sanaari Spoken Arabic",
  "Saraiki",
  "Serbian",
  "Serbo-Croatian",
  "Shona",
  "Sindhi",
  "Sinhalese",
  "Somali",
  "South Azeerbaijani",
  "South Levantine Arabic",
  "Southern Min",
  "Spnaish",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tagalog (Filipino)",
  "Ta'izzi-Adeni Arabic",
  "Tamil",
  "Telugu",
  "Thai",
  "Tunisian arabic",
  "Turkish",
  "Turkmen",
  "Ukranian",
  "Urdu",
  "Uyghur",
  "Vietnamese",
  "Welsh",
  "Western Punjabi",
  "Western Punjabi (Lahnda)",
  "Wu chinese",
  "Xhosa",
  "Xiang Chinese",
  "Yoruba",
  "Yue (inc. Cantonese)",
  "Zhuang",
  "Zulu",
];

export default languages;
